### ISSUE TITLE
Use only localhost for block notify port

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/btcd-cli4j#5]
The server listening for block notifications should  by default only listen on localhost.

@Emzy Could you add your suggestion?

**Comment by mrosseel** [comment]
as a heads up, this PR which was merged a few days ago makes the host configurable on which the rpc calls are done : 
https://github.com/bisq-network/bisq/pull/2983

Note: this is the server calling btcd, not the block notify listen which your issue is about.

If callers are to be restricted, please consider making it configurable! 
Easiest way I can think oft is to use the already configured rpchost so that btcd restricts it to whatever the seednode asks it to, which would be localhost if not configured otherwise.

**Comment by Emzy** [comment]
This needs to be fixed in btcd-cli4j. There the listen network socked is opened.

This is how I think it should work. The listen host needs to be configurable if someone needs this on an other interface listen. 

https://github.com/priiduneemre/btcd-cli4j/compare/master...Emzy:patch-1

Additionally it is good to run a firewall on the seednode. Like 

`iptables -A INPUT -i lo -j ACCEPT && iptables -A INPUT -p tcp --dport 22 -j ACCEPT && iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT && iptables -P INPUT DROP`
